# Generated by Django 6.0.6 on 2026-06-17 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_stock_qty', models.IntegerField(default=0)),
                ('product_code_sku', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
