# Generated by Django 6.0.6 on 2026-06-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_ean',
            field=models.IntegerField(default=0),
        ),
    ]
