# Generated by Django 6.0.6 on 2026-06-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_product_product_ean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_ean',
            field=models.CharField(max_length=13),
        ),
    ]
